version: "3"
services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data/product_data.csv:/home/jovyan/data/product_data.csv
      - ./data/product_image_data.csv:/home/jovyan/data/product_image_data.csv
      - ./SemanticSearch1k.ipynb:/home/jovyan/SemanticSearch1k.ipynb
      - ./VisualSearch1k.ipynb:/home/jovyan/VisualSearch1k.ipynb
      - ./VisualSearch100k.ipynb:/home/jovyan/VisualSearch100k.ipynb
      - ./SemanticSearch100k.ipynb:/home/jovyan/SemanticSearch100k.ipynb
      - ./100k-image-vectors.npy:/home/jovyan/100k-image-vectors.npy
      - ./100k-item-keyword-vectors.npy:/home/jovyan/100k-item-keyword-vectors.npy
  vecsim:
    image: redislabs/redisearch:2.4.3
    ports:
      - "6379:6379"
